version: '2.1'
services:
  sap_api_gateway:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      SAP_PROFILE_MS_API_HOST: 'ec2-3-210-210-169.compute-1.amazonaws.com'
      SAP_PROFILE_MS_API_PORT: '8000'
      SAP_PROFILE_MS_API_ENTRY: 'api/User/'
    ports:
      - '5000:5000'